[BE] 비디오 ObjectStorage에 올리기
boostcamp-2020/Project13-Web-Video-Editor pull request #7
Opened 2020-11-19 04:19 UTC by mjseok

# 개요
-비디오 파일 Object Storage에 올리기

# 체크리스트
- [x] 로컬의 파일을 선택해서(FE) 파일을 변환해서 Object Storage에 보낼 수 있다.(BE,multer모듈 사용)
- [x] save 버튼을 누르면 Object Storage에 올라간다.

2020-11-19 05:05 UTC, kyu9341 requested changes
고생하셨습니다~ 리뷰 확인 부탁드려요!

2020-11-19 05:05 UTC, kyu9341 commented on server/src/main/services/video/uploadVideo.ts
> +const uploadVideo = async (req: any, res: express.Response) => {
req객체도 `any`타입보다는 res객체처럼 `@types/express`에서 제공해주는 `req: express.Request`타입으로 받아주는 것이 좋지 않을까요?

2020-11-19 05:05 UTC, kyu9341 commented on server/src/main/services/video/uploadVideo.ts
> +import express from 'express';
라우터에서 바로 서비스를 미들웨어로 호출하는데, 컨트롤러를 만들어서 컨트롤러가 서비스를 사용하는 식으로 변경해주는 것이 좋을 것 같아요!

2020-11-19 05:09 UTC, joh16 commented on server/src/main/services/video/uploadVideo.ts
> +const region = process.env.ACCESS_KEY;
직관적으로 와닿지 않는 코드인데, 혹시 S3의 인자를 region으로 받는데 access_key 가 region 역할도 하는 건가요?

2020-11-19 05:10 UTC, joh16 commented on server/src/main/services/video/setMulter.ts
> +  upload.single('video')(req, res, next);
async는 있는데 await이 없네요?

2020-11-19 05:11 UTC, kyu9341 commented on server/src/main/services/video/uploadVideo.ts
> +};
`async`, `await`과 `promise` 가 혼용되어 있는데 `async`, `await`으로 통일하는 것이 좋지 않을까요??

2020-11-19 05:12 UTC, joh16 commented on server/src/main/services/video/uploadVideo.ts
> +    .promise()
.then, .catch를 쓰실 거라면 async 함수로 선언하신 이유가 무엇인가요?

2020-11-19 05:17 UTC, joh16 commented on server/src/main/services/video/uploadVideo.ts
> +      } else res.sendStatus(500);
status code가 500이 아닌게 왔다면 그것을 500으로 반환하는 이유는 무엇인가요?

2020-11-20 02:02 UTC, SSH1997 approved these changes
ObjectStorage 작업고생하셨습니다

2020-11-20 02:02 UTC, kyu9341 approved these changes
고생하셨습니다~

2020-11-20 02:03 UTC, merged

2020-11-20 02:03 UTC, joh16 approved these changes
Refactoring 고생하셨어요~